src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="Post")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=120)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @ORM\PreRemove
     */
    public function setCreatedAtValue()
    {
        $filePointer ='uploads/post/'.$this->image;
        return unlink($filePointer);
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Category;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title')
            ->add('category', EntityType::class, [
                'class' => Category::class
            ])
            ->add('attachment', FileType::class, [
                'mapped' => false,
                'label' => 'Image'
            ])
            ->add('save', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Post;
use App\Repository\PostRepository;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use App\Form\PostType;
use Symfony\Component\HttpFoundation\Request;

class PostController extends AbstractController
{
    /**
    * @Route("/", name="post_index")
    */
    public function index(PostRepository $postRepository)
    {
        $posts = $postRepository->findAll();
        $controller_name = 'PostsController';

        return $this->render('post/index.html.twig', compact(['posts', 'controller_name']));
    }

    /**
    * @Route("/create", name="post_create")
    */
    public function create(Request $request)
    {
        $post = new Post();

        $form = $this->createForm(PostType::class, $post);

        $form->handleRequest($request);

        if($form->isSubmitted())
        {
            $em = $this->getDoctrine()->getManager();

            /** @var UploadedFile $file */
            $file = $request->files->get('post');
            $file = $file['attachment'];

            if ($file) {
                $filename = md5(uniqid()) . '.' . $file->guessClientExtension();
                $file->move(
                    $this->getParameter('uploads_dir') ,
                    $filename
                );

                $post->setImage($filename);
            }

            $em -> persist($post);
            $em -> flush();

            $this->addFlash('success', "post: {$post->getTitle()}, was created");
            return $this->redirect($this->generateUrl("post_index"));
        }


        return $this->render('post/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
    * @Route("/show/{id}", name="post_show")
    * @ParamConverter("post", class="App\Entity\Post")
    */
    public function show($id, PostRepository $postRepository)
    {
        $post = $postRepository->findPostWithCategory($id);

        dd($post);

        return $this->render('post/show.html.twig', compact('post'));
    }
    /**
    * @Route("/delete/{id}", name="post_delete", methods={"DELETE"})
    * @ParamConverter("post", class="App\Entity\Post")
    */
    public function delete(Post $post)
    {
        $em = $this->getDoctrine()->getManager();

        $em->remove($post);
        $em->flush();

        $this->addFlash('success', 'Post was removed');

        return $this->redirect($this->generateUrl('post_index'));
    }
}

templates/post/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid" style="width:80%;">
        <div class="row justify-content-center">
            <div class="col-4 justify-content-center">
                {{ form_start(form) }}

                <div class="row form-group">
                        {{ form_label(form.Title) }}
                        {{ form_widget(form.Title) }}
                </div>

                <div class="row form-group">
                        {{ form_label(form.category) }}
                        {{ form_widget(form.category) }}
                </div>

                <div class="row form-group">
                        {{ form_label(form.attachment) }}
                        {{ form_widget(form.attachment) }}
                </div>

                <div class="row form-group justify-content-center">
                        {{ form_widget(form.save) }}
                </div>

                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% for messege in app.flashes('success') %}
        <div class="alert alert-success">
            {{ messege }}
        </div>
    {% endfor %}
    <div class="container-fluid" style="width:80%;">
        <h1>List of All Posts</h1>
        <div class="row justify-content-center">
            <table class="table table-striped">
                <thead>
                    <td>ID</td>
                    <td>Title</td>
                    <td>Action</td>
                </thead>
                <tbody>
                    {% for post in posts %}
                        <tr>
                            <td><a href="{{ path('post_show', {id: post.id}) }}">{{ post.id }}</a></td>
                            <td class="px-0">{{ post.title }}</td>
                            <td class="px-0">
                                <form class="form-group" action="{{ path('post_delete', { id: post.id }) }}" method="post">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <div class="col-2 ml-0 pl-0">
                                        <input class="form-control is-invalid" type="submit" value="delete">
                                    </div>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container-fluid" style="width:80%;">
    <div class="row justify-content-center">
        <div class="col-12 d-flex justify-content-center">
            <h1> {{ post.title }} </h1>
        </div>
        <div class="col-8 d-flex justify-content-center">
            <img src="{{'/uploads/post/' ~ post.image }}" class="w-100">
        </div>
        <div class="col-12 d-flex justify-content-center">
                <h2> {{ post.category }} </h2>
        </div>
    </div>
</div>
{% endblock %}